### ISSUE TITLE
Add extra guided jumps

### ISSUE THREAD

**Issue by jbzdarkid** [apple1417/Talos-Sigil-Randomizer#5]
- [x] A5 Things To Do With Two Boxes Star
- [x] C3 Three Little Connectors and a Fan
- [x] C4 Throne Room
- [x] C6 Circumlocution
- [x] C7 Crisscross Conundrum Advanced

**Comment by apple1417** [comment]
- [x] Floor 3 Floor Skip
- [x] Floor 4 Floor Skip
- [x] Floor 5 Floor Skip
